# Generated by Django 5.1.5 on 2025-01-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
                ("mobileOS", models.CharField(max_length=20)),
                ("educationUse", models.CharField(max_length=100)),
                ("activities", models.JSONField()),
                ("helpfulForStudying", models.CharField(max_length=200)),
                ("educationalApps", models.JSONField()),
                ("dailyUsage", models.CharField(max_length=20)),
                ("usageDistraction", models.CharField(max_length=200)),
                ("usefulFeatures", models.JSONField()),
                ("beneficialSubjects", models.JSONField()),
                ("usageSymptoms", models.JSONField()),
                ("symptomFrequency", models.CharField(max_length=100)),
                ("healthPrecautions", models.JSONField()),
            ],
        ),
    ]
