# Generated by Django 5.1.5 on 2025-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdata",
            name="performanceImpact",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
